name = "flmintdeal-frontend"
compatibility_date = "2024-08-25"
pages_build_output_dir = "./dist"

[env.production.vars]
PUBLIC_STRAPI_URL = "https://flmintdeal.fly.dev"

[env.preview.vars]
PUBLIC_STRAPI_URL = "https://flmintdeal.fly.dev"