steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flmintdeals:$COMMIT_SHA', './flmintdeals']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flmintdeals:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flmintdeals'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flmintdeals:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:flmintdeals-db'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_CLIENT=postgres,INSTANCE_UNIX_SOCKET=/cloudsql/$PROJECT_ID:us-central1:flmintdeals-db'

images:
  - 'gcr.io/$PROJECT_ID/flmintdeals:$COMMIT_SHA'