# Fly.io configuration for Strapi backend
app = "flmintdeals-backend"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  HOST = "0.0.0.0"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.checks]
    [http_service.checks.alive]
      type = "http"
      interval = "15s"
      timeout = "2s"
      path = "/_health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "1gb"