# Fly.io configuration for Strapi backend (Development)
app = "flmintdeal-dev"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.dev"

[env]
  NODE_ENV = "development"
  HOST = "0.0.0.0"
  PORT = "1337"
  PUBLIC_URL = "https://flmintdeal-dev.fly.dev"
  STRAPI_ADMIN_BACKEND_URL = "https://flmintdeal-dev.fly.dev"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    type = "http"
    interval = "30s"
    timeout = "10s"
    path = "/_health"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "1gb"