# Fly.io configuration for Astro frontend
app = "flmintdeal-frontend"
primary_region = "iad"

[build]

[env]
  PUBLIC_STRAPI_URL = "https://flmintdeal.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    type = "http"
    interval = "15s"
    timeout = "2s"
    path = "/"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1